import { Task } from "@/types/task";
import { Project } from "@/types/project";

export const tasks: Task[] = [
  {
    id: "1",
    title: "Write API Documentation",
    status: "todo",
    priority: "high",
    assignee: "Admin",
    assigneeInitial: "A",
    dueDate: "29 Jul",
    labels: ["Deployment", "Documentation"],
  },
  {
    id: "2",
    title: "Implement Search Function",
    status: "todo",
    priority: "medium",
    assignee: "Admin",
    assigneeInitial: "A",
    dueDate: "29 Jul",
    labels: ["Frontend", "Search"],
  },
  {
    id: "3",
    title: "Deploy to Production",
    status: "todo",
    priority: "high",
    assignee: "Admin",
    assigneeInitial: "A",
    dueDate: "29 Jul",
    labels: ["Deployment"],
  },
  {
    id: "4",
    title: "Code Review Completed",
    status: "doing",
    priority: "medium",
    assignee: "Admin",
    assigneeInitial: "A",
    dueDate: "29 Jul",
    labels: ["Review"],
  },
  {
    id: "5",
    title: "Design Mockups Finalized",
    status: "doing",
    priority: "high",
    assignee: "Admin",
    assigneeInitial: "A",
    dueDate: "29 Jul",
    labels: ["Design"],
  },
  {
    id: "6",
    title: "Feature Testing Passed",
    status: "completed",
    priority: "high",
    assignee: "QA Team",
    assigneeInitial: "Q",
    dueDate: "30 Jul",
    labels: ["Testing", "Passed"],
  },
  {
    id: "7",
    title: "UI Design Updated",
    status: "completed",
    priority: "medium",
    assignee: "Designer",
    assigneeInitial: "D",
    dueDate: "31 Jul",
    labels: ["Design", "Updated"],
  },
  {
    id: "8",
    title: "Security Audit Scheduled",
    status: "completed",
    priority: "medium",
    assignee: "Security",
    assigneeInitial: "S",
    dueDate: "01 Aug",
    labels: ["Audit", "Scheduled"],
  },
  {
    id: "9",
    title: "UI Review",
    status: "on-hold",
    priority: "low",
    assignee: "Designer",
    assigneeInitial: "D",
    dueDate: "02 Aug",
    labels: ["Review"],
  },
  {
    id: "10",
    title: "Backend Integration",
    status: "on-hold",
    priority: "medium",
    assignee: "Dev Team",
    assigneeInitial: "D",
    dueDate: "03 Aug",
    labels: ["Development"],
  },
];

export const projects: Project[] = [
  {
    id: "project-1",
    name: "Website Redesign",
    description:
      "Redesign and improve the company website experience.",
    status: "active",
    members: ["Admin", "Designer", "Dev Team"],
    taskCount: 12,
    completedTasks: 7,
    dueDate: "15 Sep",
  },
  {
    id: "project-2",
    name: "Mobile Application",
    description:
      "Development of the new mobile application.",
    status: "active",
    members: ["Admin", "Dev Team", "QA Team"],
    taskCount: 18,
    completedTasks: 9,
    dueDate: "30 Sep",
  },
  {
    id: "project-3",
    name: "Marketing Campaign",
    description:
      "Plan and execute the upcoming marketing campaign.",
    status: "active",
    members: ["Admin", "Designer"],
    taskCount: 10,
    completedTasks: 6,
    dueDate: "20 Sep",
  },
  {
    id: "project-4",
    name: "Security Audit",
    description:
      "Review application security and resolve identified issues.",
    status: "completed",
    members: ["Security", "Admin"],
    taskCount: 8,
    completedTasks: 8,
    dueDate: "01 Aug",
  },
  {
    id: "project-5",
    name: "Legacy Migration",
    description:
      "Migrate legacy services to the new architecture.",
    status: "on-hold",
    members: ["Dev Team"],
    taskCount: 14,
    completedTasks: 4,
    dueDate: "10 Oct",
  },
];