import { Task } from "@/types/task";

export const tasks: Task[] = [
  {
    id: "1",
    title: "Write API Documentation",
    status: "todo",
    priority: "high",
    assignee: "Admin",
    assigneeInitial: "A",
    dueDate: "29 Jul",
    labels: ["Deployment", "Deployment"],
  },
  {
    id: "2",
    title: "Implement Search Function",
    status: "todo",
    priority: "medium",
    assignee: "Admin",
    assigneeInitial: "A",
    dueDate: "29 Jul",
    labels: ["Deployment", "Deployment"],
  },
  {
    id: "3",
    title: "Deploy to Production",
    status: "todo",
    priority: "high",
    assignee: "Admin",
    assigneeInitial: "A",
    dueDate: "29 Jul",
    labels: ["Deployment", "Deployment"],
  },

  {
    id: "4",
    title: "Code Review Completed",
    status: "doing",
    priority: "medium",
    assignee: "Admin",
    assigneeInitial: "A",
    dueDate: "29 Jul",
    labels: ["Deployment", "Deployment"],
  },
  {
    id: "5",
    title: "Design Mockups Finalized",
    status: "doing",
    priority: "high",
    assignee: "Admin",
    assigneeInitial: "A",
    dueDate: "29 Jul",
    labels: ["Deployment", "Deployment"],
  },

  {
    id: "6",
    title: "Feature Testing Passed",
    status: "completed",
    priority: "high",
    assignee: "QA Team",
    assigneeInitial: "Q",
    dueDate: "30 Jul",
    labels: ["Testing", "Passed"],
  },
  {
    id: "7",
    title: "UI Design Updated",
    status: "completed",
    priority: "medium",
    assignee: "Designer",
    assigneeInitial: "D",
    dueDate: "31 Jul",
    labels: ["Design", "Updated"],
  },
  {
    id: "8",
    title: "Security Audit Scheduled",
    status: "completed",
    priority: "medium",
    assignee: "Security",
    assigneeInitial: "S",
    dueDate: "01 Aug",
    labels: ["Audit", "Scheduled"],
  },

  {
    id: "9",
    title: "UI Review",
    status: "on-hold",
    priority: "low",
    assignee: "Designer",
    assigneeInitial: "D",
    dueDate: "02 Aug",
    labels: ["Review"],
  },
  {
    id: "10",
    title: "Backend Integration",
    status: "on-hold",
    priority: "medium",
    assignee: "Dev Team",
    assigneeInitial: "D",
    dueDate: "03 Aug",
    labels: ["Development"],
  },
];